name: Link Check
on:
  workflow_dispatch: null
  schedule:
    - cron: "45 15 * * *"

permissions:
  contents: read
  security-events: write

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: Link Check
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@91ab88e2619ed1f46221f0ba42d1492c02baf788 # v6.0.6
        with:
          run_install: true
          standalone: true
      - run: pnpm exec textlint src/content/post/*.md --rule no-dead-link -f @microsoft/eslint-formatter-sarif -o textlint.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: textlint.sarif
          category: textlint
