name: Claude OAuth

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Authorization code (leave empty for step 1)'
        required: false

permissions:
  actions: write  # Required for cache management
  contents: read  # Required for basic repository access

jobs:
  auth:
    permissions:
      actions: write
      contents: read
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: grll/claude-code-login@c936f1bc69d8ddf5eb415d251f88092f671cbe83 # v1
        with:
          code: ${{ inputs.code }}
          secrets_admin_pat: ${{ secrets.SECRETS_ADMIN_PAT }}
